name: DEBUG ProjectsV2
on: workflow_dispatch

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}   # ← важно!
          script: |
            const org = 'fra1m-dev';
            const q = `query($org:String!){
              organization(login:$org){
                projectsV2(first:50){ nodes{ id number title } }
              }
            }`;
            const r = await github.graphql(q, { org });
            console.log('VISIBLE PROJECTS:', r.organization?.projectsV2?.nodes ?? []);
